name: Generate Accounts

on:
  push:
  workflow_dispatch:
    inputs:
      country:
        description: 'Select name country (IN/US)'
        required: true
        default: 'IN'
        type: choice
        options:
        - IN
        - US

jobs:
  generate-accounts:
    runs-on: ubuntu-latest
    env:
      COUNTRY: ${{ inputs.country }}
      # CORRECTED: Use secrets directly without env declaration
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install requests faker apprise

    - name: Generate accounts
      env:
        # SECURITY: Pass webhook as environment variable
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        python account_generator.py $COUNTRY
